=== xatapult/component-inventory/grammar/ci-specification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="https://eriksiegel.nl/ns/component-inventory"
  xmlns:ci="https://eriksiegel.nl/ns/component-inventory" vc:minVersion="1.1" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
  xmlns:sml="http://www.eriksiegel.nl/ns/sml">

  <xs:include schemaLocation="ci-common.mod.xsd"/>
  <xs:import namespace="http://www.eriksiegel.nl/ns/sml" schemaLocation="../../xtpxlib-sml/xsd/sml.xsd"/>
  <xs:element name="component-inventory-specification">
    <xs:complexType>
      <xs:sequence>
        <xs:group minOccurs="0" ref="ci:g-macrodefs"/>
        <xs:element name="properties">
          <xs:complexType>
            <xs:sequence>
              <xs:group minOccurs="0" ref="ci:g-macrodefs"/>
              <xs:element maxOccurs="unbounded" minOccurs="0" name="property">
                <xs:complexType>
                  <xs:complexContent>
                    <xs:extension base="ci:ct-definition">
                      <xs:attribute name="value-pattern" type="ci:t-regexp">
                        <xs:annotation>
                          <xs:documentation>A regular expression for the value to match. If absent or empty, anything goes.</xs:documentation>
                        </xs:annotation>
                      </xs:attribute>
                      <xs:attribute name="default" type="xs:string">
                        <xs:annotation>
                          <xs:documentation>The default value for the property.</xs:documentation>
                        </xs:annotation>
                      </xs:attribute>
                      <xs:attribute name="suffix" type="ci:t-non-empty-string">
                        <xs:annotation>
                          <xs:documentation>An optional suffix, always appened to the end of the value.</xs:documentation>
                        </xs:annotation>
                      </xs:attribute>
                    </xs:extension>
                  </xs:complexContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="categories" type="ci:ct-categories"/>
        <xs:element name="price-ranges">
          <xs:complexType>
            <xs:sequence>
              <xs:group minOccurs="0" ref="ci:g-macrodefs"/>
              <xs:element maxOccurs="unbounded" minOccurs="0" name="price-range">
                <xs:complexType>
                  <xs:complexContent>
                    <xs:extension base="ci:ct-definition">
                      <xs:attribute name="min-inclusive" type="ci:t-price" use="required"/>
                      <xs:attribute name="max-inclusive" type="ci:t-price" use="required"/>
                    </xs:extension>
                  </xs:complexContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="packages">
          <xs:complexType>
            <xs:sequence>
              <xs:group minOccurs="0" ref="ci:g-macrodefs"/>
              <xs:element maxOccurs="unbounded" minOccurs="0" name="package">
                <xs:complexType>
                  <xs:complexContent>
                    <xs:extension base="ci:ct-definition">
                      <xs:sequence>
                        <xs:group minOccurs="0" ref="ci:g-media"/>
                      </xs:sequence>
                    </xs:extension>
                  </xs:complexContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attributeGroup ref="ci:ag-default-base-directory"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="locations">
          <xs:complexType>
            <xs:sequence>
              <xs:group minOccurs="0" ref="ci:g-macrodefs"/>
              <xs:element maxOccurs="unbounded" minOccurs="0" name="location" type="ci:ct-definition"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="components">
          <xs:complexType>
            <xs:sequence>
              <xs:group minOccurs="0" ref="ci:g-macrodefs"/>
              <xs:element maxOccurs="unbounded" minOccurs="0" name="directory">
                <xs:annotation>
                  <xs:documentation>Search this directory, and all its sub-directories, for components.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:attribute name="href" type="ci:t-href-directory" use="required"/>
                  <xs:attribute name="component-description-document-regexp" type="ci:t-regexp" default="^component-.+\.xml$">
                    <xs:annotation>
                      <xs:documentation>The regular expression for the documents that contain a component description.</xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attributeGroup ref="ci:ag-default-base-directory"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="ct-categories">
    <xs:sequence>
      <xs:group minOccurs="0" ref="ci:g-macrodefs"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="category">
        <xs:complexType>
          <xs:complexContent>
            <xs:extension base="ci:ct-definition">
              <xs:sequence>
                <xs:element minOccurs="0" name="categories">
                  <xs:complexType>
                    <xs:complexContent>
                      <xs:extension base="ci:ct-categories">
                        <xs:attribute default="false" name="sub-category-mandatory" type="xs:boolean">
                          <xs:annotation>
                            <xs:documentation>Whether a sub-category is mandatory here.</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                      </xs:extension>
                    </xs:complexContent>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
              <xs:attribute name="mandatory-property-idrefs">
                <xs:annotation>
                  <xs:documentation>When this category is used, these properties must have a value (either the default or something filled in).</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                  <xs:list itemType="ci:t-identifier"/>
                </xs:simpleType>
              </xs:attribute>
              <xs:attribute name="optional-property-idrefs">
                <xs:annotation>
                  <xs:documentation>When this category is used, it is optional to fill in these properties.</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                  <xs:list itemType="ci:t-identifier"/>
                </xs:simpleType>
              </xs:attribute>
            </xs:extension>
          </xs:complexContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== xatapult/component-inventory/test/test-specification-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="../grammar/ci-specification.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<component-inventory-specification xmlns="https://eriksiegel.nl/ns/component-inventory" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:sml="http://www.eriksiegel.nl/ns/sml" xsi:schemaLocation="https://eriksiegel.nl/ns/component-inventory ../grammar/ci-specification.xsd">

  <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

  <properties>
    <property id="VOLTAGE" value-pattern="^[0-9][0-9]*$"/>
    <property id="CONTACTS" value-pattern="^[0-9][0-9]*$"/>
    <property id="CURRENT" value-pattern="^[0-9][0-9]*$"/>
    <property id="RELAYTYPE" value-pattern="^(NORMAL|SPECIAL)$" default="NORMAL"/>
  </properties>

  <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

  <categories>

    <category id="ICS" name="ICs" summary="Integrated circuits" mandatory-property-idrefs="VOLTAGE" optional-property-idrefs="CURRENT">
      <categories sub-category-mandatory="true">
        <category id="LOGIC" name="Logic ICs"/>
        <category id="OPAMP" name="Opamp ICs"/>
      </categories>
    </category>

    <category id="RELAYS" name="Relays" mandatory-property-idrefs="VOLTAGE CONTACTS" optional-property-idrefs="CURRENT RELAYTYPE">
      <categories sub-category-mandatory="false">
        <category id="SMALL" name="Small relays"/>
        <category id="BIG" name="Big relays"/>
      </categories>
    </category>

  </categories>

  <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

  <price-ranges>
    <price-range min-inclusive="0.0" max-inclusive="1" id="cheap"/>
    <price-range min-inclusive="1.1" max-inclusive="5" id="midprice"/>
  </price-ranges>

  <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

  <packages href-default-base-directory="../resources/packaging/">
    <package id="DIP16"/>
    <!--<package id="DIP14"/>-->
    <package id="RELAY"/>
  </packages>

  <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

  <locations>
    <location id="BOX" name="Box" summary="Box on the shelf"/>
    <location id="BOX2" name="Box 2" summary="Another box on the shelf"/>
  </locations>

  <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

  <components>
    <directory href="components-2/" component-description-document-regexp="^component-.+\.xml$"/>
  </components>

</component-inventory-specification>
